// <auto-generated />
using System;
using ECom.Services.Billing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECom.Services.Billing.Migrations
{
    [DbContext(typeof(ReceiptDbContext))]
    partial class ReceiptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECom.Services.Billing.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int")
                        .HasColumnName("cost");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("status");

                    b.Property<string>("VoucherCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("voucher_code");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 500000,
                            Date = new DateTime(2023, 12, 8, 13, 29, 1, 311, DateTimeKind.Local).AddTicks(6069),
                            OrderId = 1,
                            PaymentMethod = "cod",
                            Status = "0",
                            VoucherCode = "ABCDEF"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 500000,
                            Date = new DateTime(2023, 12, 8, 13, 29, 1, 311, DateTimeKind.Local).AddTicks(6085),
                            OrderId = 2,
                            PaymentMethod = "cod",
                            Status = "1",
                            VoucherCode = "ABCDEF"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
