// <auto-generated />
using System;
using ECom.Services.Reports.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECom.Services.Reports.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    partial class ReportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECom.Services.Reports.Models.DailyReport", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("Date")
                        .HasColumnName("date");

                    b.Property<long>("Income")
                        .HasColumnType("bigint")
                        .HasColumnName("income");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("Date")
                        .HasColumnName("month");

                    b.Property<long>("Outcome")
                        .HasColumnType("bigint")
                        .HasColumnName("outcome");

                    b.Property<long>("Profit")
                        .HasColumnType("bigint")
                        .HasColumnName("profit");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int")
                        .HasColumnName("sold_quantity");

                    b.HasKey("Date");

                    b.HasIndex("Month");

                    b.ToTable("DailyReports");

                    b.HasData(
                        new
                        {
                            Date = new DateOnly(2023, 12, 1),
                            Income = 500000L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 80000L,
                            Profit = 400830L,
                            SoldQuantity = 5
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 2),
                            Income = 5520100L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 400800L,
                            Profit = 4328830L,
                            SoldQuantity = 50
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 3),
                            Income = 2014000L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 442500L,
                            Profit = 1524830L,
                            SoldQuantity = 20
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 4),
                            Income = 2140000L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 210800L,
                            Profit = 1258830L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 5),
                            Income = 32500000L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 4000800L,
                            Profit = 36228830L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 6),
                            Income = 9600000L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 520800L,
                            Profit = 9218830L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 7),
                            Income = 12025200L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 4042800L,
                            Profit = 8518830L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 8),
                            Income = 54740000L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 41200L,
                            Profit = 2418830L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 9),
                            Income = 12400000L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 440800L,
                            Profit = 1423830L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 10),
                            Income = 14250000L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 456486L,
                            Profit = 8451246L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 11),
                            Income = 4675652L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 656264L,
                            Profit = 6542642L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 12),
                            Income = 64865224L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 864564L,
                            Profit = 65634266L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 13),
                            Income = 4263164L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 6542164L,
                            Profit = 6464568L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 14),
                            Income = 456462161L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 756576L,
                            Profit = 56746264L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 15),
                            Income = 45642621L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 5648646L,
                            Profit = 546465L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 16),
                            Income = 54642562L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 4566456L,
                            Profit = 54648626L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 17),
                            Income = 56426321L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 564568L,
                            Profit = 26456876L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 18),
                            Income = 45621654L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 456878L,
                            Profit = 5464562L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 19),
                            Income = 126126568L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 5462161L,
                            Profit = 7865612L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 20),
                            Income = 4562166L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 45642L,
                            Profit = 4564566L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 21),
                            Income = 4564876L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 126456L,
                            Profit = 2134566L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 22),
                            Income = 56766754L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 937388L,
                            Profit = 35835677L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 23),
                            Income = 35675476L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 465849L,
                            Profit = 763457L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 24),
                            Income = 4363464L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 400800L,
                            Profit = 4328830L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 25),
                            Income = 2342351L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 542554L,
                            Profit = 2312424L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 26),
                            Income = 23523566L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 234241L,
                            Profit = 5474724L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 27),
                            Income = 24754645L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 2525563L,
                            Profit = 3135153L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 28),
                            Income = 23564436L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 2352546L,
                            Profit = 4564754L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 29),
                            Income = 3463467L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 3457378L,
                            Profit = 3453253L,
                            SoldQuantity = 500
                        },
                        new
                        {
                            Date = new DateOnly(2023, 12, 30),
                            Income = 2365464L,
                            Month = new DateOnly(2023, 12, 1),
                            Outcome = 3464685L,
                            Profit = 3452352L,
                            SoldQuantity = 500
                        });
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.DailyReportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("Date")
                        .HasColumnName("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("DailyReportDetail");
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.MonthlyReport", b =>
                {
                    b.Property<DateOnly>("Month")
                        .HasColumnType("Date")
                        .HasColumnName("month");

                    b.Property<long>("Income")
                        .HasColumnType("bigint")
                        .HasColumnName("income");

                    b.Property<long>("Outcome")
                        .HasColumnType("bigint")
                        .HasColumnName("outcome");

                    b.Property<long>("Profit")
                        .HasColumnType("bigint")
                        .HasColumnName("profit");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("int")
                        .HasColumnName("sold_quantity");

                    b.Property<DateOnly>("Year")
                        .HasColumnType("Date")
                        .HasColumnName("year");

                    b.HasKey("Month");

                    b.HasIndex("Year");

                    b.ToTable("MonthlyReports");

                    b.HasData(
                        new
                        {
                            Month = new DateOnly(2023, 1, 1),
                            Income = 50000000L,
                            Outcome = 4000800L,
                            Profit = 4328830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 2, 1),
                            Income = 4200000L,
                            Outcome = 40800L,
                            Profit = 432830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 3, 1),
                            Income = 55808000L,
                            Outcome = 4000800L,
                            Profit = 4328830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 4, 1),
                            Income = 5080000L,
                            Outcome = 4005800L,
                            Profit = 43258830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 5, 1),
                            Income = 23000000L,
                            Outcome = 5140800L,
                            Profit = 3288306L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 6, 1),
                            Income = 542540000L,
                            Outcome = 4133500L,
                            Profit = 4328830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 7, 1),
                            Income = 41360000L,
                            Outcome = 7530800L,
                            Profit = 4328830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 8, 1),
                            Income = 1430000L,
                            Outcome = 300800L,
                            Profit = 3228830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 9, 1),
                            Income = 32320000L,
                            Outcome = 400800L,
                            Profit = 4322830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 10, 1),
                            Income = 223300000L,
                            Outcome = 53658800L,
                            Profit = 46568830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 11, 1),
                            Income = 50000000L,
                            Outcome = 4000800L,
                            Profit = 4328830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        },
                        new
                        {
                            Month = new DateOnly(2023, 12, 1),
                            Income = 50000000L,
                            Outcome = 4000800L,
                            Profit = 4328830L,
                            SoldQuantity = 500,
                            Year = new DateOnly(2023, 1, 1)
                        });
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.YearlyReport", b =>
                {
                    b.Property<DateOnly>("Year")
                        .HasColumnType("Date")
                        .HasColumnName("year");

                    b.Property<long>("Income")
                        .HasColumnType("bigint")
                        .HasColumnName("income");

                    b.Property<long>("Outcome")
                        .HasColumnType("bigint")
                        .HasColumnName("outcome");

                    b.Property<long>("Profit")
                        .HasColumnType("bigint")
                        .HasColumnName("profit");

                    b.Property<long>("SoldQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("sold_quantity");

                    b.HasKey("Year");

                    b.ToTable("YearlyReports");

                    b.HasData(
                        new
                        {
                            Year = new DateOnly(2023, 1, 1),
                            Income = 5000000000L,
                            Outcome = 490000800L,
                            Profit = 4903928830L,
                            SoldQuantity = 50000L
                        });
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.DailyReport", b =>
                {
                    b.HasOne("ECom.Services.Reports.Models.MonthlyReport", "MonthlyReport")
                        .WithMany("DailyReports")
                        .HasForeignKey("Month")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthlyReport");
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.DailyReportDetail", b =>
                {
                    b.HasOne("ECom.Services.Reports.Models.DailyReport", "DailyReport")
                        .WithMany("Details")
                        .HasForeignKey("Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyReport");
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.MonthlyReport", b =>
                {
                    b.HasOne("ECom.Services.Reports.Models.YearlyReport", "YearlyReport")
                        .WithMany("MonthlyReports")
                        .HasForeignKey("Year")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YearlyReport");
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.DailyReport", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.MonthlyReport", b =>
                {
                    b.Navigation("DailyReports");
                });

            modelBuilder.Entity("ECom.Services.Reports.Models.YearlyReport", b =>
                {
                    b.Navigation("MonthlyReports");
                });
#pragma warning restore 612, 618
        }
    }
}
